[book]
title = "PowerView Help"
authors = ["Morten Bogetvedt", "Henrik Bækhus"]
language = "en"
description = "Help system for Prediktor PowerView"

[build]
create-missing = true
build-dir = "book"

[output.html]
theme = "theme"
mathjax-support = true
copy-fonts = false

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding
