[book]
title = "PowerView Help"
authors = ["Morten Bogetvedt", "Henrik Bækhus"]
language = "en"
description = "Help system for Prediktor PowerView"
multilingual = false
src = "src"

[output.html]
theme = "theme"
no-section-label = true
copy-fonts = false

[build]
create-missing = true
build-dir = "book"

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0        # the depth to start folding