# Sample workflow for building and deploying a mdBook site to GitHub Pages
#
# To get started with mdBook see: https://rust-lang.github.io/mdBook/index.html
#
name: Test mdBook

on: [push]

jobs:

  # Build job
  build:

    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.28
    steps:
      - uses: actions/checkout@v3
      - name: Install mdBook
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -y | sh
          rustup update
          cargo install --version ${MDBOOK_VERSION} mdbook
      - name: Test with mdBook
        run: mdbook test
